language: python
sudo: required
dist: xenial
before_install:
- chmod +x .travis/*.sh
matrix:
  include:
  - env: IMG="ubuntu1604"
    python:
    - 3.6
    install:
    - ".travis/install-ubuntu.sh"
    script:
    - ".travis/build-py36.sh"
    - ".travis/release.sh"
  - env: IMG="ubuntu1604"
    python:
    - 2.7
    install:
    - ".travis/install-ubuntu.sh"
    script:
    - ".travis/build-py27.sh"
    - ".travis/release.sh"
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c"
    services:
    - docker
    # for logging purposes
    python:
    - 3.6
    before_install:
    - chmod +x .travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e TRAVIS_TAG="${TRAVIS_TAG}" ${OS} tail -f /dev/null
    - docker ps
    install:
    - $SH .travis/install-centos.sh
    script:
    - $SH .travis/build-py36-centos.sh
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c"
    services:
    - docker
    # for logging purposes
    python:
    - 2.7
    before_install:
    - chmod +x .travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e TRAVIS_TAG="${TRAVIS_TAG}" ${OS} tail -f /dev/null
    - docker ps
    install:
    - $SH .travis/install-centos.sh
    script:
    - $SH .travis/build-py27.sh
    - $SH .travis/release.sh
deploy:
  provider: releases
  api_key:
    secure: pUrnMi4YtRwxQ75K1HJaXSUaPdvd5+CMVzWnS2zUZeC5TNXMgCSpAYVLFMV2xOJZiZ4WIKW4i/oin9nYJ24wPFhCYmeMj6b71u1BJbG02PXBgEcIZrQhcNHEi1E/tv8pYx4aPx1FbNELnH2iV5QsYZbUf+SFWOLUkbe1nVPrKU4eRJiXbJJNgewlvNcePM3EXPQNxTSWg9Pwnh1zO/RRl/mXqZNptMgdfx5jvWeO+/wrKXxW8sxUzAt4zFOTUK/0a6kw5Cn033fgFwYl02x3ux182dQ5Oqb0LLGNfQFTa+hr8cuCVKwzIyU9zJrUXxQaoW6hUMtm8FH5LFDbXPLnClEEoAvaU1PYslATYSo5KGcEOqzPGsrPgYvqtdoG1KhSlO4nDv478akf6rj5gzbb2mUzbBScl6u+nYTK91HshdDlrf3vHIbbd1KU0MTSAdEZeDhOQmiX/t7zgaYQ7NxliLSf6HUD1ARUiMRnWN9Xb6/UGLK+6RtAoYWdW//bJCZi8p/w3LhpnzSTT1fv/bWQQxFuNbiYijsjgk9SHyghPimVF0PhJr2UooiwYkb0d3IOO7WO2vBJbvT69+nm2X8Tt+6L3/zzmvhs1yb4zz5w7osc/F4vJGyhoQruyBvfSTGhh3AvUyc+EayjsVhqD6rkYtUkINcN1aBATCIN4ytIsn0=
  file_glob: true
  file: release/*.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: adobe-apiplatform/user-sync.py
    all_branches: true
