environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      BUILD_TARGET: pex
    - PYTHON: "C:\\Python36-x64"
      BUILD_TARGET: pex
    - PYTHON: "C:\\Python36-x64"
      BUILD_TARGET: standalone

install:
- ps: choco install make

build_script:
- ps: .build\.appveyor\build.ps1

test_script:
- ps: .build\.appveyor\test.ps1

artifacts:
- path: release/*.zip
  name: Zips
- path: release/*.tar.gz
  name: Tarballs
- path: release/*.exe
  name: Executables
